"""empty message

Revision ID: 3ce5ddf9cde0
Revises: d1dc3472ba1e
Create Date: 2023-04-09 13:16:17.468864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce5ddf9cde0'
down_revision = 'd1dc3472ba1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('is_faq')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_faq', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
