"""empty message

Revision ID: 69719cce73c4
Revises: 
Create Date: 2023-04-07 19:03:33.164836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69719cce73c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('profile_picture', sa.String(length=1000), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'SUPPORT_STAFF', 'ADMIN', name='role'), server_default='STUDENT', nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'DEACTIVATED', name='account_status'), server_default='ACTIVE', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('active_session',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('ver_code', sa.String(length=1000), nullable=False),
    sa.Column('login_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_access_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tag_title', sa.String(length=200), nullable=False),
    sa.Column('created_by_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_title')
    )
    op.create_table('ticketfiles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=5000), nullable=False),
    sa.Column('created_by_id', sa.Text(), nullable=False),
    sa.Column('attached_to', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='status'), server_default='ACTIVE', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('created_by_id', sa.Text(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_offensive', sa.Boolean(), nullable=True),
    sa.Column('is_faq', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='status'), server_default='ACTIVE', nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'), server_default='LOW', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_staff_tags',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('tag_id', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_staff_tickets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_tags',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tag_id', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'ticket_id', name='_ticket_vote_uc')
    )
    op.create_table('ticketreplies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('reply', sa.String(length=5000), nullable=False),
    sa.Column('created_by_id', sa.Text(), nullable=False),
    sa.Column('is_answer', sa.Boolean(), nullable=True),
    sa.Column('is_offensive', sa.Boolean(), nullable=True),
    sa.Column('reply_to', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='status'), server_default='ACTIVE', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticketvotes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=False),
    sa.Column('vote', sa.Enum('UP', 'DOWN', name='vote_type'), server_default='UP', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticket_id', name='_ticket_vote_uc')
    )
    op.create_table('repliesvotes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('reply_id', sa.Text(), nullable=False),
    sa.Column('vote', sa.Enum('UP', 'DOWN', name='vote_type'), server_default='UP', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['ticketreplies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reply_id', name='_reply_vote_uc')
    )
    op.create_table('tracker_edit_ticket',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('old_obj', sa.String(), nullable=True),
    sa.Column('new_obj', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.Text(), nullable=True),
    sa.Column('reply_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['ticketreplies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker_edit_ticket')
    op.drop_table('repliesvotes')
    op.drop_table('ticketvotes')
    op.drop_table('ticketreplies')
    op.drop_table('ticket_tags')
    op.drop_table('support_staff_tickets')
    op.drop_table('support_staff_tags')
    op.drop_table('tickets')
    op.drop_table('ticketfiles')
    op.drop_table('tags')
    op.drop_table('active_session')
    op.drop_table('user')
    # ### end Alembic commands ###
