"""empty message

Revision ID: 93b55cc9b104
Revises: 69719cce73c4
Create Date: 2023-04-07 20:14:33.079750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b55cc9b104'
down_revision = '69719cce73c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='status'), server_default='ACTIVE', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
