"""empty message

Revision ID: d1dc3472ba1e
Revises: 93b55cc9b104
Create Date: 2023-04-07 20:34:38.024419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1dc3472ba1e'
down_revision = '93b55cc9b104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_staff_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='status'), server_default='ACTIVE', nullable=True))
        batch_op.add_column(sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('support_staff_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='status'), server_default='ACTIVE', nullable=True))
        batch_op.add_column(sa.Column('last_updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_staff_tickets', schema=None) as batch_op:
        batch_op.drop_column('last_updated_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('support_staff_tags', schema=None) as batch_op:
        batch_op.drop_column('last_updated_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
